# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a30b89c15b665eb5f93c4b777b82888d80884c44c73a66303538745228e70ce01daf4f0f8b0da49483dbb38c9629d70f63c8117a2759759e679ae4d08e11c443

test:
  secret_key_base: 41277224db03e8f7044f72bb342fa0548cd1cd8d8f9c19a69d84a8f350848efbb0817e8c26e89c05e910ef9cf935d62fd4b10bedb982009f0cfae9cf62cdc4f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
